version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
    pull-request-branch-name:
      separator: "-"
