[tool.black]
line-length = 100
target-version = ['py313']
include = '\.pyi?$'
extend-exclude = '''
/(
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.ruff]
target-version = "py313"
line-length = 100

[tool.ruff.lint]
select = [
    "E",  
    "W", 
    "F",  
    "I",  
    "B",  
    "C4", 
    "UP", 
]
ignore = [
    "E501",  
    "B008",
    "C901",
    "F821"
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]