services:
  plex-tvtime-py:
    image: ghcr.io/0xsysr3ll/plex-tvtime-py:latest
    container_name: plex-tvtime-py
    labels:
      traefik.enable: true
      traefik.http.routers.plex-tvtime-py.rule: Host(`tvtime.example.com`)
      traefik.http.routers.plex-tvtime-py.entrypoints: https
      traefik.http.routers.plex-tvtime-py.tls: true
      traefik.http.services.plex-tvtime-py.loadbalancer.server.port: 5000
      traefik.http.routers.plex-tvtime-py.middlewares: "default@file"
      traefik.docker.network: "traefik_backend"
    environment:
      - TZ=Etc/UTC # Set your timezone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    configs:
      - source: tvtime_config
        target: /app/config/config.yml
    networks:
      traefik_backend:

configs:
  tvtime_config:
    file: ./config/config.yml
networks:
  traefik_backend:
    external: true